---
# Author: Felipe Pfeifer Rubin
# Contact: felipe.rubin@edu.pucrs.br

# Shared Network: eth0 (Vagrant Only)
# Management Network: Used by Ansible and is also the main interface for intra-node communication.
# Provider Network KVM:[provider] -> [provider]:Gateway:<NAT>[WAN] -> Internet
# Overlay Network: For use with Linux Bridges, no Internet access.
# Steps:
# 1. Vagrant up configures eth0, and each node Management Network
# 2. Ansible uses the management network to configure the Provider Network and Overlay Network
# 3. Openstack uses both networks


- name: gateway # Public Faced Host
  box: bento/ubuntu-18.04
  mem: 2048
  cpu: 2
  linkedclone: true
  nestedvt: false
  # namelabel: true
  # x11: true
  # gui: false
  # vram: 256
  video3d: true
  network:
    - kind: private_network # NIC:eth1, Management Network (Host Only)  NIC: eth1
      ip: 10.0.0.2 
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, WAN Interface, Internet Gateway with 'Public' IP,
      bridge: en8 # Wireless Card
      auto_config: true
    - kind: public_network # NIC:eth3, Provider Network
      bridge: en8 # Ethernet Card
      auto_config: false

- name: datastore # Storage Node
  mem: 4096
  cpu: 2
  linkedclone: true
  nestedvt: false
  network:
    - kind: private_network # NIC:eth1, Management Network (Host Only)
      ip: 10.0.0.3
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, Provider Network
      bridge: en8 # Ethernet Card
      auto_config: false
    - kind: public_network # NIC:eth3, Overlay Network (Linux Bridge)
      bridge: en8 # Ethernet Card
      auto_config: false
  disk:
    - size: 50 # Block Storage (size in GB)


# The controller needs a lot of memory.
# It is the center of all communications and management as well as
# hosts the MySQL Database.
# When executing with 4GB of RAM, for example, it eventually crashes
# due to low few resources available for MySQL.
- name: control # Controller Node (also networking)
  mem: 8192
  cpu: 2
  linkedclone: true
  nestedvt: false
  network:
    - kind: private_network # NIC:eth1, Management Network (Host Only)
      ip: 10.0.0.4
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, Provider Network
      bridge: en8 # Ethernet Card
      auto_config: false
    - kind: public_network # NIC:eth3, Overlay Network (Linux Bridge)
      bridge: en8 # Ethernet Card
      auto_config: false


# Compute Nodes, hypervisors with nested virtualization enabled.

- name: kvm1 # Compute Node 1
  mem: 4096
  cpu: 2
  linkedclone: true
  nestedvt: true
  3dvideo: true
  vram: 128
  network:
    - kind: private_network # NIC:eth1, Management Network (Host Only)
      ip: 10.0.0.5
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, Provider Network
      bridge: en8 # Ethernet Card
      auto_config: false
    - kind: public_network # NIC:eth3, Overlay Network (Linux Bridge)
      bridge: en8 # Ethernet Card
      auto_config: false

- name: kvm2 # Compute Node 2
  mem: 2048
  cpu: 2
  linkedclone: true
  nestedvt: true
  network:
    - kind: private_network # NIC:eth1, Management Network (Host Only)
      ip: 10.0.0.6
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, Provider Network
      bridge: en8 # Ethernet Card
      auto_config: false
    - kind: public_network # NIC:eth3, Overlay Network (Linux Bridge)
      bridge: en8 # Ethernet Card
      auto_config: false

